export const GET_COMMUNITY = 'SMILEAPP/COMMUNITY/GET_COMMUNITY';
export const GET_COMMUNITY_SUCCESS = 'SMILEAPP/COMMUNITY/GET_COMMUNITY_SUCCESS ';
export const GET_COMMUNITY_FAILURE = 'SMILEAPP/COMMUNITY/GET_COMMUNITY_FAILURE ';
