export const GET_DASHBOARD_DATA = 'SMILEAPP/DASHBOARD/GET_DASHBOARD_DATA';
export const GET_DASHBOARD_DATA_SUCCESS = 'SMILEAPP/DASHBOARD/GET_DASHBOARD_DATA_SUCCESS ';
export const GET_DASHBOARD_DATA_FAILURE = 'SMILEAPP/DASHBOARD/GET_DASHBOARD_DATA_FAILURE ';
