export const GET_DASHBOARD_DATA = 'SMILEAPP/DASHBOARD/GET_DASHBOARD_DATA';
export const GET_DASHBOARD_DATA_SUCCESS = 'SMILEAPP/DASHBOARD/GET_DASHBOARD_DATA_SUCCESS ';
export const GET_DASHBOARD_DATA_FAILURE = 'SMILEAPP/DASHBOARD/GET_DASHBOARD_DATA_FAILURE ';
export const UPDATE_SMILE_DATA = 'SMILEAPP/DASHBOARD/UPDATE_SMILE_DATA';
export const RESET_SMILE_DATA= 'SMILEAPP/DASHBOARD/RESET_SMILE_DATA';
