export const POST_STEP_TWO = 'SMILEAPP/QUOTE/POST_STEP_TWO';
export const POST_STEP_TWO_SUCCESS = 'SMILEAPP/QUOTE/POST_STEP_TWO_SUCCESS ';
export const POST_STEP_TWO_FAILURE = 'SMILEAPP/QUOTE/POST_STEP_TWO_FAILURE ';
