export const LOGIN = 'SMILEAPP/App/LOGIN';
export const SET_USER_INFO = 'SMILEAPP/App/SET_USER_INFO';
export const SET_AUTH_TOKEN = 'SMILEAPP/App/SET_AUTH_TOKEN';
export const LOGIN_FAILURE = 'SMILEAPP/App/LOGIN_FAILURE';
export const LOGOUT = 'SMILEAPP/App/LOGOUT';
export const RESET_SERVER_ERROR = 'SMILEAPP/App/RESET_SERVER_ERROR';
export const USER_LOGIN_SOCIAL_REQUESTED = 'SMILEAPP/App/USER_LOGIN_SOCIAL_REQUESTED';