# Generated by Django 2.2.19 on 2021-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=300)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
