# Generated by Django 2.2.19 on 2021-03-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='create_at',
            new_name='created',
        ),
    ]
