# Generated by Django 2.2.19 on 2021-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210309_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
