# Generated by Django 2.2.19 on 2021-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_smile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
