# Generated by Django 2.2.19 on 2021-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210309_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smile',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
