# Generated by Django 2.2.19 on 2021-03-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210315_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
