# Generated by Django 2.2.19 on 2021-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_smileexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='smileexercise',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
