# Generated by Django 2.2.19 on 2021-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_smileexercise_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmileCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='smile_community')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
