# Generated by Django 2.2.19 on 2021-04-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_game_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='second',
            new_name='game_second',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='second',
            new_name='level_second',
        ),
    ]
