# Generated by Django 2.2.19 on 2021-04-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210408_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
