# Generated by Django 2.2.20 on 2021-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210408_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilescience',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smilescience',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
