# Generated by Django 2.2.20 on 2021-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210426_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smilescience',
            name='is_favorites',
        ),
        migrations.RemoveField(
            model_name='smilescience',
            name='title',
        ),
        migrations.AddField(
            model_name='smileexercise',
            name='exercise_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smileexercise',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
