# Generated by Django 2.2.20 on 2021-04-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_auto_20210426_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smileexercise',
            name='is_favorites',
        ),
        migrations.CreateModel(
            name='FavoriteExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('favorite_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='dashboard.SmileExercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
