# Generated by Django 2.2.24 on 2021-06-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210629_0638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmileScience',
        ),
    ]
