# Generated by Django 2.2.24 on 2021-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_delete_smilescience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smileexercise',
            name='image_or_video',
            field=models.FileField(upload_to='media/smile_exercise'),
        ),
    ]
