# Generated by Django 2.2.24 on 2021-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20210629_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smileexercise',
            name='image_or_video',
            field=models.FileField(upload_to='smile_exercise/'),
        ),
    ]
