# Generated by Django 2.2.24 on 2021-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20210629_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='image',
            field=models.ImageField(upload_to='smile_community'),
        ),
    ]
