# Generated by Django 2.2.24 on 2021-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210702_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('smile_science', 'Smile_Science'), ('community', 'Community'), ('notification', 'Notification'), ('Level', 'Level')], max_length=50, null=True),
        ),
    ]
