# Generated by Django 2.2.24 on 2021-07-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('smile science', 'Smile Science'), ('community', 'Community'), ('notification', 'Notification'), ('Level', 'Level')], max_length=50, null=True),
        ),
    ]
