# Generated by Django 2.2.24 on 2021-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20210705_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('Smile Science', 'Smile Science'), ('Community', 'Community'), ('Notification', 'Notification'), ('Level', 'Level')], max_length=50, null=True),
        ),
    ]
