# Generated by Django 2.2.24 on 2021-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
