# Generated by Django 2.2.24 on 2021-07-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20210705_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='total_second',
        ),
    ]
