# Generated by Django 2.2.24 on 2021-07-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
