export default {
  logos: require('src/assets/images/logos.png'),
  loginbg: require('src/assets/images/loginbg.png'),
  google: require('src/assets/images/google.png'),
  facebook: require('src/assets/images/facebook.png'),
  instagram: require('src/assets/images/instagram.png'),
  pass: require('src/assets/images/pass.png'),
  age: require('src/assets/images/age.png'),
  gender: require('src/assets/images/gender.png'),
  relation: require('src/assets/images/relation.png'),
  child: require('src/assets/images/child.png'),
  profession: require('src/assets/images/profession.png'),
  email: require('src/assets/images/email.png'),
  buttonBg: require('src/assets/images/buttonBg.png'),
  toggle: require('src/assets/images/toggle.png'),
  user: require('src/assets/images/user.png'),
  dashboard: require('src/assets/images/dashboard.png'),
  splash: require('src/assets/images/splash.png'),

  homelight: require('src/assets/images/home-light.png'),
  homedark: require('src/assets/images/home-dark.png'),
  goalslight: require('src/assets/images/goals-light.png'),
  goalsdark: require('src/assets/images/goals-dark.png'),
  statslight: require('src/assets/images/stats-light.png'),
  statsdark: require('src/assets/images/stats-dark.png'),
  gameslight: require('src/assets/images/games-light.png'),
  gamesdark: require('src/assets/images/games-dark.png'),
  morelight: require('src/assets/images/more-light.png'),
  moredark: require('src/assets/images/more-dark.png'),
}
