export default {
  logos: require('src/assets/images/logos.png'),
  loginbg: require('src/assets/images/loginbg.png'),
  google: require('src/assets/images/google.png'),
  facebook: require('src/assets/images/facebook.png'),
  instagram: require('src/assets/images/instagram.png'),
  pass: require('src/assets/images/pass.png'),
  age: require('src/assets/images/age.png'),
  gender: require('src/assets/images/gender.png'),
  relation: require('src/assets/images/relation.png'),
  child: require('src/assets/images/child.png'),
  profession: require('src/assets/images/profession.png'),
  email: require('src/assets/images/email.png'),
  buttonBg: require('src/assets/images/buttonBg.png'),
  toggle: require('src/assets/images/toggle.png'),
  togglewhite: require('src/assets/images/togglewhite.png'),
  user: require('src/assets/images/user.png'),
  dashboard: require('src/assets/images/dashboard.png'),
  splash: require('src/assets/images/splash.png'),
  progresicon: require('src/assets/images/progresicon.png'),
  camera: require('src/assets/images/camera.png'),
  money: require('src/assets/images/money.png'),
  slider1: require('src/assets/images/slider1.png'),
  slider2: require('src/assets/images/slider2.png'),
  game1: require('src/assets/images/game1.png'),
  game2: require('src/assets/images/game2.png'),
  share: require('src/assets/images/share.png'),
  homelight: require('src/assets/images/home-light.png'),
  homedark: require('src/assets/images/home-dark.png'),
  goalslight: require('src/assets/images/goals-light.png'),
  goalsdark: require('src/assets/images/goals-dark.png'),
  statslight: require('src/assets/images/stats-light.png'),
  statsdark: require('src/assets/images/stats-dark.png'),
  gameslight: require('src/assets/images/games-light.png'),
  gamesdark: require('src/assets/images/games-dark.png'),
  morelight: require('src/assets/images/more-light.png'),
  moredark: require('src/assets/images/more-dark.png'),
  exercisesdark: require('src/assets/images/exercises-dark.png'),
  exerciseslight: require('src/assets/images/exercises-light.png'),
  dashboard1bg: require('src/assets/images/dashboard1bg.png'),
  signupbg: require('src/assets/images/signupbg.png'),
  screenbg: require('src/assets/images/screenbg.png'),
  smile: require('src/assets/images/smile.png'),
  camerabg: require('src/assets/images/camerabg.png'),
  arrowback: require('src/assets/images/arrow-back.png'),
  camarrowback: require('src/assets/images/cam-arrow-back.png'),
  record: require('src/assets/images/record.png'),
  gallery: require('src/assets/images/gallery-icon.png'),
  filterimg1: require('src/assets/images/filterimg1.png'),
  filterimg2: require('src/assets/images/filterimg2.png'),
  filterimg3: require('src/assets/images/filterimg3.png'),
  filterimg4: require('src/assets/images/filterimg4.png'),
  quote: require('src/assets/images/quote.png'),
  quote: require('src/assets/images/quote.png'),
  playlight: require('src/assets/images/play-light.png'),
  playdark: require('src/assets/images/play-dark.png'),
  musiclight: require('src/assets/images/music-light.png'),
  musicdark: require('src/assets/images/music-dark.png'),
  quotelight: require('src/assets/images/quote-light.png'),
  quotedark: require('src/assets/images/quote-dark.png'),
  originallight: require('src/assets/images/original-light.png'),
  originaldark: require('src/assets/images/original-dark.png'),
  gallerylight: require('src/assets/images/gallery-light.png'),
  gallerydark: require('src/assets/images/gallery-dark.png'),
  preference: require('src/assets/images/preference-icon.png'),
  camsetting: require('src/assets/images/cam-setting.png'),
  quote: require('src/assets/images/quote.png'),
  cam: require('src/assets/images/cam.png'),
  levelbox: require('src/assets/images/levelbox.png'),
  lateststreak: require('src/assets/images/lateststreak.png'),
  maxstreak: require('src/assets/images/maxstreak.png'),
  dots: require('src/assets/images/dots.png'),
  more1: require('src/assets/images/moreimg1.png'),
  more3: require('src/assets/images/moreimg3.png'),
  more2: require('src/assets/images/moreimg2.png'),
  smilingrest: require('src/assets/images/smilingrest.png'),
  star: require('src/assets/images/star.png'),
  articalimage1: require('src/assets/images/ArticalImage1.png'),
  articalimage2: require('src/assets/images/ArticalImage2.png'),
  articalimage3: require('src/assets/images/ArticalImage3.png'),
  articalimage4: require('src/assets/images/ArticalImage4.png'),
  articalimage5: require('src/assets/images/ArticalImage5.png'),
  articalimage6: require('src/assets/images/ArticalImage6.png'),
  progressimage: require('src/assets/images/progressimage.png'),
  progressimagegolden: require('src/assets/images/progressimagegolden.png'),
  communityimage1: require('src/assets/images/communityimage1.png'),
  communityimage2: require('src/assets/images/communityimage2.png'),
  communityimage3: require('src/assets/images/communityimage3.png'),
  polygon: require('src/assets/images/Polygon.png'),
  streak: require('src/assets/images/streak.png'),
  notification: require('src/assets/images/notification.png'),
  community: require('src/assets/images/community.png'),
  smilescience: require('src/assets/images/smilescience.png'),
  level: require('src/assets/images/level.png'),
  levels: require('src/assets/images/levels.png'),
  activityicon: require('src/assets/images/activityicon.png'),
  moreoption: require('src/assets/images/moredotted.png'),
  polygonDwon: require('src/assets/images/polygon.png'),
  starfav: require('src/assets/images/starfav.png'),
  eye: require('src/assets/images/eye.png'),
  userprofile: require('src/assets/images/userprofilepic.png'),
  profilecam: require('src/assets/images/userprofile.png'),

  // first dashboard
  // homelight: require('src/assets/dashboard/homelight.png'),
  // homedark: require('src/assets/dashboard/homedark.png'),
  // goalslight: require('src/assets/dashboard/goalslight.png'),
  // goalsdark: require('src/assets/dashboard/goalsdark.png'),
  // statslight: require('src/assets/dashboard/statslight.png'),
  // statsdark: require('src/assets/dashboard/statsdark.png'),
  // gameslight: require('src/assets/dashboard/gameslight.png'),
  // gamesdark: require('src/assets/dashboard/gamesdark.png'),
  // morelight: require('src/assets/dashboard/morelight.png'),
  // moredark: require('src/assets/dashboard/moredark.png'),

  // second dashboard
  homelight: require('src/assets/more/home-light.png'),
  homedark: require('src/assets/more/home-dark.png'),
  goalslight: require('src/assets/more/goals-light.png'),
  goalsdark: require('src/assets/more/goals-dark.png'),
  statslight: require('src/assets/more/stats-light.png'),
  statsdark: require('src/assets/more/stats-dark.png'),
  // gameslight: require('src/assets/more/games-light.png'),
  // gamesdark: require('src/assets/more/games-dark.png'),
  morelight: require('src/assets/more/more-light.png'),
  moredark: require('src/assets/more/more-dark.png'),
  activitiesdark: require('src/assets/more/activities-dark.png'),
  activitieslight: require('src/assets/more/activities-light.png'),
}
