export const GET_EXERCISES_ACTIVITIES =
  'SMILEAPP/ACTIVITIES/GET_EXERCISES_ACTIVITIES';
export const GET_EXERCISES_ACTIVITIES_SUCCESS =
  'SMILEAPP/ACTIVITIES/GET_EXERCISES_ACTIVITIES_SUCCESS ';
export const GET_EXERCISES_ACTIVITIES_FAILURE =
  'SMILEAPP/ACTIVITIES/GET_EXERCISES_ACTIVITIES_FAILURE ';

export const SELECT_ACTIVITIES = 'SMILEAPP/ACTIVITIES/SELECT_ACTIVITIES';
export const SELECT_ACTIVITIES_SUCCESS =
  'SMILEAPP/ACTIVITIES/SMILEAPP/SELECT_ACTIVITIES_SUCCESS ';
export const SELECT_ACTIVITIES_FAILURE =
  'SMILEAPP/ACTIVITIES/SMILEAPP/SELECT_ACTIVITIES_FAILURE ';
