export const POST_STEP_THREE = 'SMILEAPP/QUOTE/POST_STEP_THREE';
export const POST_STEP_THREE_SUCCESS = 'SMILEAPP/QUOTE/POST_STEP_THREE_SUCCESS ';
export const POST_STEP_THREE_FAILURE = 'SMILEAPP/QUOTE/POST_STEP_THREE_FAILURE ';
