export const POST_STEP_THREE = 'SMILEAPP/STEPS/POST_STEP_THREE';
export const POST_STEP_THREE_SUCCESS = 'SMILEAPP/STEPS/POST_STEP_THREE_SUCCESS ';
export const POST_STEP_THREE_FAILURE = 'SMILEAPP/STEPS/POST_STEP_THREE_FAILURE ';
export const SET_AUTH_TOKEN = 'SMILEAPP/App/SET_AUTH_TOKEN';
