export const GET_MORE_RESOURCES = 'SMILEAPP/MORE_RESOURCES/GET_MORE_RESOURCES';
export const GET_MORE_RESOURCES_SUCCESS = 'SMILEAPP/MORE_RESOURCES/GET_MORE_RESOURCES_SUCCESS ';
export const GET_MORE_RESOURCES_FAILURE = 'SMILEAPP/MORE_RESOURCES/GET_MORE_RESOURCES_FAILURE ';
