export const GET_PROFILE = 'SMILEAPP/QUOTE/GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'SMILEAPP/PROFILE/GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'SMILEAPP/PROFILE/GET_PROFILE_FAILURE';

export const UPDATE_PROFILE = 'SMILEAPP/PROFILE/UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'SMILEAPP/PROFILE/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'SMILEAPP/PROFILE/UPDATE_PROFILE_FAILURE';
