export const GET_EXERCISES = 'SMILEAPP/EXERCISES/GET_EXERCISES';
export const GET_EXERCISES_SUCCESS = 'SMILEAPP/EXERCISES/GET_EXERCISES_SUCCESS ';
export const GET_EXERCISES_FAILURE = 'SMILEAPP/EXERCISES/GET_EXERCISES_FAILURE ';
export const MARK_FAVOURITE = 'SMILEAPP/MARK_FAVOURITE';
