# Generated by Django 2.2.19 on 2021-03-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.CharField(choices=[(4, 'I want to increase happiness'), (5, 'I want to express gratitude'), (6, 'I want an energy boost'), (7, 'I want to feel more confident')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(choices=[(2, 'Married'), (3, 'Unmarried')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
