# Generated by Django 2.2.24 on 2021-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210629_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession_status',
            field=models.CharField(blank=True, choices=[(14, 'Employee'), (15, 'UnEmployee'), (16, 'Business')], max_length=50, null=True),
        ),
    ]
