# Generated by Django 2.2.24 on 2021-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210629_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[(3, 'Married'), (4, 'Unmarried')], max_length=100, null=True),
        ),
    ]
