# Generated by Django 2.2.24 on 2021-06-30 14:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210629_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'I want to increase happiness'), (1, 'I want to express gratitude'), (2, 'I want an energy boost'), (3, 'I want to feel more confident'), (4, 'I want to feel more relaxed'), (5, 'I want to feel peace'), (6, 'I want to reduce stress'), (7, 'I want to calm anxiety'), (8, 'I want to lower my blood pressure/heart rate')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[(0, 'Married'), (1, 'Unmarried')], max_length=100, null=True),
        ),
    ]
