# Generated by Django 2.2.24 on 2021-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210630_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession_status',
            field=models.CharField(blank=True, choices=[(0, 'Employee'), (1, 'UnEmployee'), (2, 'Business')], max_length=50, null=True),
        ),
    ]
