# Generated by Django 2.2.24 on 2021-07-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
