export const GET_SCIENCE = 'SMILEAPP/SCIENCE/GET_SCIENCE';
export const GET_SCIENCE_SUCCESS = 'SMILEAPP/SCIENCE/GET_SCIENCE_SUCCESS ';
export const GET_SCIENCE_FAILURE = 'SMILEAPP/SCIENCE/GET_SCIENCE_FAILURE ';
